# Generated by Django 3.1.2 on 2021-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_token', '0002_auto_20210405_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_key',
            field=models.TextField(max_length=350, unique=True),
        ),
    ]
