# Generated by Django 3.1.2 on 2021-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_token', '0005_auto_20210522_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_key',
            field=models.TextField(),
        ),
    ]
