# Generated by Django 3.1.5 on 2021-04-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['created_at']},
        ),
    ]
