# Generated by Django 3.1.5 on 2021-04-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_auto_20210329_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['doctor']},
        ),
    ]
