# Generated by Django 3.1.5 on 2021-02-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('dental_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctors.doctor'),
        ),
    ]
