# Generated by Django 3.1.2 on 2021-03-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210303_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttable',
            options={'ordering': ['-created_at']},
        ),
    ]
