# Generated by Django 3.1.2 on 2021-04-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210327_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttable',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
